[build]
command = "npm run build"
publish = ".output/server/index.mjs"
# functions = "dist/functions/"

# [dev]
#  command = " dev"
# targetPort = 5173

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
