export const farms = [
  {
    name: "Butter Stick",
    initialCost: 3.738,
    coefficient: 1.07,
    initialTime: 0.6,
    initialProductivity: 1.67,
    unlockCookieAmount: 10,
    unlocked: false,
    unlockMessage: "you learn how to exploit butter",
    owned: 0,
  },
  {
    name: "Chocolate Bar",
    initialCost: 60.0,
    coefficient: 1.15,
    initialTime: 3,
    initialProductivity: 20,
    unlockCookieAmount: 50,
    unlockMessage: "you make your own chocolate now?",
    unlocked: false,
    owned: 0,
  },
  {
    name: "Veggplants",
    initialCost: 720.0,
    coefficient: 1.14,
    initialTime: 6,
    initialProductivity: 90,
    unlockCookieAmount: 540,
    unlocked: false,
    unlockMessage: "Eggs from plants?!",
    owned: 0,
  },
  {
    name: "Sugar Clouds",
    initialCost: 8640.0,
    coefficient: 1.13,
    initialTime: 12,
    initialProductivity: 360,
    unlockCookieAmount: 4320,
    unlocked: false,
    unlockMessage: "You invent Sugar Clouds!",
    owned: 0,
  },
  {
    name: "Vanilli",
    initialCost: 103680.0,
    coefficient: 1.12,
    initialTime: 24,
    initialProductivity: 2160.0,
    unlockCookieAmount: 51840,
    unlocked: false,
    unlockMessage: "Vanili joins forces!",
    owned: 0,
  },
];

export const debugFarms = [
  {
    name: "Butter Stick",
    initialCost: 1,
    coefficient: 1.0,
    initialTime: 0.6,
    initialProductivity: 1.67,
    unlockCookieAmount: 2,
    unlocked: false,
    unlockMessage: "you learn how to exploit butter",
    owned: 0,
  },
  {
    name: "Chocolate Bar",
    initialCost: 6.0,
    coefficient: 1.15,
    initialTime: 3,
    initialProductivity: 20,
    unlockCookieAmount: 5,
    unlockMessage: "you make your own chocolate now?",
    unlocked: false,
    owned: 0,
  },
  {
    name: "Veggplants",
    initialCost: 72.0,
    coefficient: 1.1,
    initialTime: 6,
    initialProductivity: 90,
    unlockCookieAmount: 8,
    unlocked: false,
    unlockMessage: "Eggs from plants?!",
    owned: 0,
  },
  {
    name: "Sugar Clouds",
    initialCost: 86.0,
    coefficient: 1.13,
    initialTime: 12,
    initialProductivity: 360,
    unlockCookieAmount: 15,
    unlocked: false,
    unlockMessage: "You invent Sugar Clouds!",
    owned: 0,
  },
  {
    name: "Vanilli",
    initialCost: 86.0,
    coefficient: 1.13,
    initialTime: 12,
    initialProductivity: 360,
    unlockCookieAmount: 18,
    unlocked: false,
    unlockMessage: "Vanili joins forces!",
    owned: 0,
  },
];
